export const products = [
    {
        id: 1,
        name: 'Marinara',
        type: 'Vegetarian',
        inCart: false,
        img: 'images/1.png',
        price: [270, 320, 350],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 270
    },
    {
        id: 2,
        name: 'Quattro Stagioni',
        type: 'Vegetarian',
        inCart: false,
        img: 'images/2.png',
        price: [280, 330, 375],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 280
    },
    {
        id: 3,
        name: 'Carbonara',
        type: 'Meat',
        inCart: false,
        img: 'images/3.png',
        price: [310, 350, 395],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 310
    },
    {
        id: 4,
        name: 'Crudo',
        type: 'Meat',
        inCart: false,
        img: 'images/4.png',
        price: [275, 300, 340],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 275
    },
    {
        id: 5,
        name: 'Pugliese',
        type: 'Meat',
        inCart: false,
        img: 'images/5.png',
        price: [315, 350, 395],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 315
    },
    {
        id: 6,
        name: 'Emiliana',
        type: 'Grill',
        inCart: false,
        img: 'images/6.png',
        price: [240, 265, 300],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 240
    },
    {
        id: 7,
        name: 'Fattoria',
        type: 'Meat',
        inCart: false,
        img: 'images/7.png',
        price: [290, 350, 420],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 290
    },
    {
        id: 8,
        name: 'Schiacciata',
        type: 'Spicy',
        inCart: false,
        img: 'images/8.png',
        price: [260, 315, 360],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 260
    },
    {
        id: 9,
        name: 'Valtellina',
        type: 'Meat',
        inCart: false,
        img: 'images/9.png',
        price: [245, 320, 345],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 245
    },
    {
        id: 10,
        name: 'Pizza al Pesto',
        type: 'Spicy',
        inCart: false,
        img: 'images/10.png',
        price:[300, 360, 415],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 300
    },
    {
        id: 11,
        name: 'Ortolana',
        type: 'Grill',
        inCart: false,
        img: 'images/11.png',
        price: [245, 300, 350],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 245
    },
    {
        id: 12,
        name: 'Capricciosa',
        type: 'Vegetarian',
        inCart: false,
        img: 'images/12.png',
        price: [225, 260, 300],
        lengthClass: 0,
        pizzaLength: ['26 см.', '30 см.', '40 см.'],
        item: 1,
        totalCost: 225
    }
]